classdef MrSeries < CopyData
%Class of MR Time Series (4D = spatial coordinates:x,y,z, and time)
%
%
% EXAMPLE
%   MrSeries
%
%   See also
%
% Author:   Saskia Klein & Lars Kasper
% Created:  2014-06-06
% Copyright (C) 2014 Institute for Biomedical Engineering
%                    University of Zurich and ETH Zurich
%
% This file is part of the Zurich fMRI Methods Evaluation Repository, which is released
% under the terms of the GNU General Public Licence (GPL), version 3. 
% You can redistribute it and/or modify it under the terms of the GPL
% (either version 3 or, at your option, any later version).
% For further details, see the file COPYING or
%  <http://www.gnu.org/licenses/>.
%
% $Id$

properties
 % COMMENT_BEFORE_PROPERTY
    name    = '';
    data    = MrImage; % contains nX*nY*nZ*nT data matrix (also called data)
    mean    = MrImage;
    sd      = MrImage;
    snr     = MrImage;
    %coeffVar = MrImage % coefficient of variation
    anatomy = MrImage;  % anatomical image for reference
    tpms    = {} %cell of MrImages, tissue probability maps
    masks   = {}; % cell of MrImages
    rois    = {}; % cell of MrRois
    processing_log = {};
    svn_version = '$Rev$'; % code version 
    nProcessingSteps = 0;
    
    % parameters for all complicated methods
    parameters = ...
        struct(...
        'trSeconds', [], ... 
        'realign', ...
            struct( ...
            'quality', 0.9 ...
            ), ...
        'smooth', struct('fwhmMillimeter', 3), ... 
        'create_masks', ...
            struct( ...
            'source', {}, ...
            'threshold', 0.9 ...
            ), ...
            'extract_rois', ...
            struct( ...
            'mode',  'statImages' ... % 'statImages', 'timeseries4d'
            ), ...
        't_filter', ...
            struct( ...
            'cutOffSeconds', 128 ...
            ), ...
        'save', ...
            struct( ...
            'path', pwd, ...
            'format', 'nii', ...
            'items', 'all' ...
        ), ...
    );
    
end % properties
 
 
methods

% Constructor of class
function this = MrSeries()
end

end % methods
 
end
